src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>Candidate&apos;s First Name</description>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vacancies__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lists all open vacancies 
where the candidate is proposed</description>
        <label>Vacancies</label>
        <referenceTo>Vacancy__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAND-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Candidate proposed for this vacancy by recruiter (Only candidates with &quot;Validated by HR&quot; status)</description>
        <label>Candidate</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Candidate__c.Status__c</field>
                <operation>equals</operation>
                <value>Validated by HR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the vacancy</description>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VacancyCandidate.cls
/**
 * Created by dmeli on 19.07.19.
 */

public with sharing class VacancyCandidate {
    List<Candidate__c> candidates = new List<Candidate__c>();

    public List<Vacancy__c> getVacanciesWithCandidate() {
        List<Vacancy__c> results = [SELECT Id,Candidate__c,Title__c FROM Vacancy__c WHERE Candidate__c != NULL];
        return results;
    }

    public void updateCandidate() {
        for (Vacancy__c currentVacancy : getVacanciesWithCandidate()) {
            candidates.add([SELECT Id,Vacancies__c,FirstName__c FROM Candidate__c WHERE Id = :currentVacancy.Candidate__c]);

            System.debug('candidates@@@@@@@@@ ----- ' + candidates);

//            for (Candidate__c currentCandidate : candidates) {
//                currentCandidate.Vacancies__c = currentVacancy.Id;
//                System.debug('CANDIDATE ----- ' + currentCandidate);
//                update currentCandidate;
//            }
        }
    }
}