src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>Candidate&apos;s First Name</description>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Candidate&apos;s status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Validated by HR</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Hired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAND-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Candidate proposed for this vacancy by recruiter (Only candidates with &quot;Validated by HR&quot; status)</description>
        <label>Candidate</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Candidate__c.Status__c</field>
                <operation>equals</operation>
                <value>Validated by HR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Vacancy status, &quot;New&quot; and &quot;In-Process&quot; are set by the system. &quot;Cancelled&quot; and &quot;Closed&quot; are available only when the vacancy is already saved and can be edited only by the Manager who opened the vacancy</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vacancy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/VacancyCandidateAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipName>VacancyCandidateAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <label>Vacancy</label>
        <referenceTo>Vacancy__c</referenceTo>
        <relationshipName>VacancyCandidateAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vacancy - Candidate relationship</label>
    <nameField>
        <displayFormat>VC-{0000}</displayFormat>
        <label>VacancyCandidateAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VacancyCandidateAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListOfCandidates.cls
/**
 * Created by dmeli on 31.07.19.
 */

public class ListOfCandidates {

    private final Vacancy__c currentVacancy;
    private List<CandidateWrapper> candidateList = new List<CandidateWrapper>();
    private List<Candidate__c> selectedCandidates = new List<Candidate__c>();
    private List<VacancyCandidateAssociation__c> vacancyCandidateAssociations = new List<VacancyCandidateAssociation__c>();
    private String confirmMessage = 'One or more candidate was updated';
    private String errorMessage = 'Select candidate';
    private Map<Integer, String> vacancyStatusPicklist = new Map<Integer, String>{
            1 => 'New', 2 => 'In-Process', 3 => 'Closed', 4 => 'Cancelled'
    };
    private Map<Integer, String> candidateStatusPicklist = new Map<Integer, String>{
            1 => 'New', 2 => 'Validated by HR', 3 => 'Hired', 4 => 'Disqualified'
    };

    public ListOfCandidates(ApexPages.StandardController stdController) {
        System.debug('123123123');
        this.currentVacancy = (Vacancy__c) stdController.getRecord();
    }

    private List<Candidate__c> getCandidates() {
        return [SELECT FirstName__c, Status__c, Name, (SELECT Vacancy__c, Candidate__c FROM VacancyCandidateAssociations__r WHERE Vacancy__c = :currentVacancy.Id) FROM Candidate__c WHERE Status__c = :candidateStatusPicklist.get(2)];
    }

    public void onLoad() {
        Vacancy__c vacancyToCheck = [SELECT Id,Name, Status__c FROM Vacancy__c WHERE Id = :currentVacancy.Id];

        if (vacancyToCheck.Status__c == vacancyStatusPicklist.get(2)) {
            for (Candidate__c c : getCandidates()) {
                if (c.VacancyCandidateAssociations__r.size() < 1) {
                    candidateList.add(new CandidateWrapper(c));
                }
            }
        }
    }

    public List<CandidateWrapper> getCandidatesToAdd() {
        return candidateList;
    }

    public PageReference getSelected() {
        selectedCandidates.clear();
        for (CandidateWrapper candidatesWrapper : candidateList) {
            if (candidatesWrapper.selected) {
                selectedCandidates.add(candidatesWrapper.candidate);
            }
        }
        return null;
    }

    public List<Candidate__c> getSelectedCandidates() {
        return selectedCandidates;
    }

    public void addCandidates() {
        if (selectedCandidates.size() > 0) {
            for (Candidate__c currentCandidate : selectedCandidates) {
                prepareToAddCandidate(currentCandidate.Id);
            }
            insert vacancyCandidateAssociations;
            currentVacancy.Status__c = vacancyStatusPicklist.get(2);
            update currentVacancy;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, confirmMessage));
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
        }
    }

    public void prepareToAddCandidate(Id CandidateId) {
        VacancyCandidateAssociation__c vacancyCandidate = new VacancyCandidateAssociation__c();
        vacancyCandidate.Vacancy__c = currentVacancy.Id;
        vacancyCandidate.Candidate__c = CandidateId;
        vacancyCandidateAssociations.add(vacancyCandidate);
    }

    public class CandidateWrapper {
        public Candidate__c candidate { get; set; }
        public Boolean selected { get; set; }
        public CandidateWrapper(Candidate__c c) {
            candidate = c;
            selected = false;
        }
    }
}